'use client';

import { useMemo } from 'react';
import type { FinalAssessment } from '@/types/interview';
import { CompetencyRadar } from './CompetencyRadar';
import { FileText, CheckCircle2, TrendingUp, AlertTriangle, MessageSquare, BrainCircuit, Users } from 'lucide-react';

interface AssessmentReportProps {
  assessment: FinalAssessment;
}

export function AssessmentReport({ assessment }: AssessmentReportProps) {
  // Convert final assessment into the format expected by CompetencyRadar
  const radarData = useMemo(() => {
    const state: Record<string, any> = {};
    for (const comp of assessment.competencies) {
      state[comp.id] = {
        rating: comp.rating,
        confidence: comp.confidence,
        difficulty: 3, // Default to 3 for final radar
      };
    }
    return state;
  }, [assessment.competencies]);

  return (
    <div className="flex flex-col gap-8 pb-12">
      {/* Header & Overall Summary */}
      <div className="flex flex-col gap-4 rounded-xl border border-border/40 bg-card p-6 shadow-sm">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary ring-1 ring-primary/20">
            <FileText className="h-5 w-5" />
          </div>
          <div className="flex flex-col">
            <h2 className="text-xl font-bold tracking-tight text-foreground">Final Assessment Report</h2>
            <p className="text-xs font-medium text-muted-foreground">Generated by AI Panel • Human Review Required</p>
          </div>
        </div>
        
        <div className="mt-2 rounded-lg bg-surface/50 p-5 ring-1 ring-border/50">
          <p className="text-sm leading-relaxed text-foreground">{assessment.overallSummary}</p>
        </div>
        
        <div className="grid gap-4 md:grid-cols-2">
          {/* Strengths */}
          <div className="flex flex-col gap-3 rounded-lg border border-border/40 bg-surface/30 p-4">
            <h3 className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-green-500">
              <CheckCircle2 className="h-4 w-4" /> Top Strengths
            </h3>
            <ul className="flex flex-col gap-2">
              {assessment.candidateSummary.strengths.map((s, i) => (
                <li key={i} className="flex items-start gap-2 text-sm text-foreground">
                  <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-green-500" />
                  <span>{s}</span>
                </li>
              ))}
            </ul>
          </div>
          
          {/* Growth Areas */}
          <div className="flex flex-col gap-3 rounded-lg border border-border/40 bg-surface/30 p-4">
            <h3 className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-amber-500">
              <TrendingUp className="h-4 w-4" /> Growth Areas
            </h3>
            <ul className="flex flex-col gap-2">
              {assessment.candidateSummary.growthAreas.map((g, i) => (
                <li key={i} className="flex items-start gap-2 text-sm text-foreground">
                  <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-amber-500" />
                  <span>{g}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>

      {/* Competencies & Radar */}
      <div className="grid gap-6 lg:grid-cols-12">
        <div className="flex flex-col rounded-xl border border-border/40 bg-card p-6 shadow-sm lg:col-span-4">
          <h3 className="mb-6 flex items-center gap-2 text-sm font-semibold tracking-tight text-foreground">
            <BrainCircuit className="h-4 w-4 text-primary" />
            Competency Profile
          </h3>
          <div className="flex justify-center pb-4">
            <CompetencyRadar competencies={radarData} size={260} />
          </div>
          <div className="mt-auto flex flex-col gap-2 border-t border-border/40 pt-4">
            <div className="text-xs text-muted-foreground">Topics covered: {assessment.coverage.covered.length}</div>
            {assessment.coverage.notObserved.length > 0 && (
              <div className="text-xs text-amber-500">Not observed: {assessment.coverage.notObserved.join(', ')}</div>
            )}
          </div>
        </div>

        <div className="flex flex-col gap-4 lg:col-span-8">
          <h3 className="flex items-center gap-2 text-sm font-semibold tracking-tight text-foreground">
            <Target className="h-4 w-4 text-primary" />
            Detailed Evidence
          </h3>
          <div className="flex flex-col gap-4">
            {assessment.competencies.map((comp) => (
              <div key={comp.id} className="flex flex-col gap-3 rounded-lg border border-border/40 bg-surface/30 p-5">
                <div className="flex items-start justify-between">
                  <div className="flex flex-col gap-1">
                    <h4 className="text-base font-semibold capitalize text-foreground">{comp.name.replace(/_/g, ' ')}</h4>
                    <p className="text-xs text-muted-foreground">{comp.summary}</p>
                  </div>
                  <div className="flex flex-col items-end gap-1">
                    <div className="flex items-center gap-1.5">
                      <span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Rating</span>
                      <span className={`rounded px-1.5 py-0.5 text-xs font-bold ${comp.rating && comp.rating >= 3 ? 'bg-green-500/10 text-green-500' : 'bg-amber-500/10 text-amber-500'}`}>
                        {comp.rating ? `${comp.rating}/4` : 'N/A'}
                      </span>
                    </div>
                    <span className="text-[10px] font-medium text-muted-foreground">Conf: {(comp.confidence * 100).toFixed(0)}%</span>
                  </div>
                </div>
                
                {comp.evidence.length > 0 && (
                  <div className="mt-2 flex flex-col gap-2 border-t border-border/20 pt-3">
                    <span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Linked Evidence</span>
                    {comp.evidence.map((ev, i) => (
                      <div key={i} className="flex items-start gap-2 rounded bg-background/50 p-2 text-xs italic text-muted-foreground ring-1 ring-border/30">
                        <MessageSquare className="mt-0.5 h-3 w-3 shrink-0 text-primary/60" />
                        "{ev.quote}"
                      </div>
                    ))}
                  </div>
                )}
                
                {comp.gaps.length > 0 && (
                  <div className="mt-1 flex flex-col gap-1.5">
                    <span className="text-[10px] font-bold uppercase tracking-wider text-amber-500">Identified Gaps</span>
                    <ul className="flex flex-col gap-1">
                      {comp.gaps.map((gap, i) => (
                        <li key={i} className="text-xs text-foreground/80">• {gap}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Role Views & Follow Ups */}
      <div className="grid gap-6 lg:grid-cols-2">
        <div className="flex flex-col gap-4 rounded-xl border border-border/40 bg-card p-6 shadow-sm">
          <h3 className="flex items-center gap-2 text-sm font-semibold tracking-tight text-foreground">
            <Users className="h-4 w-4 text-primary" />
            Panel Role Perspectives
          </h3>
          <div className="flex flex-col gap-4">
            {assessment.roleViews.map((view, i) => (
              <div key={i} className="flex flex-col gap-1.5 border-l-2 border-primary pl-3">
                <span className="text-xs font-bold uppercase tracking-wider text-primary">{view.role.replace(/_/g, ' ')}</span>
                <p className="text-sm text-foreground">{view.summary}</p>
              </div>
            ))}
          </div>
        </div>

        <div className="flex flex-col gap-6">
          {assessment.unresolvedContradictions.length > 0 && (
            <div className="flex flex-col gap-4 rounded-xl border border-destructive/30 bg-destructive/5 p-6 shadow-sm">
              <h3 className="flex items-center gap-2 text-sm font-semibold tracking-tight text-destructive">
                <AlertTriangle className="h-4 w-4" />
                Unresolved Contradictions
              </h3>
              <ul className="flex flex-col gap-2">
                {assessment.unresolvedContradictions.map((c, i) => (
                  <li key={i} className="text-sm text-foreground">• {c}</li>
                ))}
              </ul>
            </div>
          )}

          <div className="flex flex-col gap-4 rounded-xl border border-border/40 bg-card p-6 shadow-sm">
            <h3 className="flex items-center gap-2 text-sm font-semibold tracking-tight text-foreground">
              <MessageSquare className="h-4 w-4 text-primary" />
              Suggested Human Follow-ups
            </h3>
            <ul className="flex flex-col gap-3">
              {assessment.suggestedHumanFollowUps.map((f, i) => (
                <li key={i} className="flex items-start gap-2 rounded bg-surface/50 p-3 text-sm text-foreground ring-1 ring-border/50">
                  <span className="mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded-full bg-primary/20 text-[10px] font-bold text-primary">
                    {i + 1}
                  </span>
                  <span>{f}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>

    </div>
  );
}

// Minimal stub since icon wasn't imported from lucide-react above
function Target({ className }: { className?: string }) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className={className}>
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="6" />
      <circle cx="12" cy="12" r="2" />
    </svg>
  );
}
